config/routes.rb
Rails.application.routes.draw do
  resources :tweet_messages, only: %i[new create edit update destroy]
  root to: redirect('/top')
  get 'top' => 'pages#top'

  get 'callback' => 'zaim_api#callback'
  get 'login_to_zaim' => 'zaim_api#login'
  get 'zaim/money' => 'zaim_api#index'
  get 'zaim/re_acquisition' => 'zaim_api#index_re_acquisition'

  get 'auth/:provider/callback' => 'sessions#create'
  get '/logout' => 'sessions#destroy', as: :logout

  get 'user/edit' => 'users#edit', as: :edit_user
  patch 'user' => 'users#update', as: :user

  # view routing errors
  match '*path' => 'application#render_404', via: :all
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Boast tweet if you can save money
    = csrf_meta_tags
    meta[name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"]
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header.navbar.my-navbar-default[role="navigation"]
      .container.container-fluid
        .navbar-header
          button[type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"]
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to '節約できたら自慢ツイート', root_path, class: 'my-navbar-brand'
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          ul.nav.my-navbar-nav.navbar-right
            - if logged_in?
              li.dropdown
                = link_to '#', class: 'dropdown-toggle header-icon-padding',
                        data: { :toggle => 'dropdown' }, role: 'button' do
                  = image_tag current_user.image_url
                  = current_user.nickname
                  ul.my-dropdown-menu[role="menu"]
                    li
                      - if coordinated_with_zaim?(current_user)
                        = link_to 'Zaimへログイン', login_to_zaim_path
                      - else
                        = link_to '支払い履歴', zaim_money_path
                    li
                      = link_to 'Twitter情報編集', edit_user_path
                    li
                      = link_to 'ログアウト', logout_path
            - else
              li
                = link_to 'Twitterでログイン', '/auth/twitter'
    .container
      - if flash[:notice]
        .alert.alert-success = flash[:notice]
      - if flash[:alert]
        .alert.alert-danger = flash[:alert]
      = yield